# -*- coding: utf-8 -*-

# RARIDADE TIER 2 (comum, bom, raro, epico, lendario)
RARITY_T2 = {
    "comum": 0.72,
    "bom": 0.25,
    "raro": 0.025,
    "epico": 0.004,
    "lendario": 0.001,
}

# TIER 2: RECEITAS DO CONJUNTO ORNAMENTADO DO BARDO (Nível de Profissão 20+)
# ============================================================================

RECIPES = {
    # --- Instrumento Magistral (Armeiro/Artífice) ---
    "work_alaude_ornamentado_bardo": {
        "display_name": "Alaúde Ornamentado do Bardo",
        "emoji": "🎻",
        "profession": "armeiro",  # se tiver "artifice" cadastrado, trocar aqui
        "level_req": 20,
        "time_seconds": 2400,
        "xp_gain": 120,
        "inputs": {"madeira_rara": 15, "seiva_de_ent": 4, "fio_de_prata": 5, "nucleo_forja_comum": 1},
        "result_base_id": "alaude_ornamentado_bardo",
        "unique": True,
        "class_req": ["bardo"],
        "rarity_chances": dict(RARITY_T2),
        "affix_pools_to_use": ["bardo", "geral"],
        "damage_info": {"type": "sonico", "min_damage": 30, "max_damage": 40},
    },

    # --- Trajes de Veludo (Alfaiate) ---
    "work_chapeu_emplumado_bardo": {
        "display_name": "Chapéu Emplumado do Bardo",
        "emoji": "🎩",
        "profession": "alfaiate",
        "level_req": 20,
        "time_seconds": 1200,
        "xp_gain": 80,
        "inputs": {"veludo_runico": 12, "fio_de_prata": 5, "pena": 25, "nucleo_forja_comum": 1},
        "result_base_id": "chapeu_emplumado_bardo",
        "unique": True,
        "class_req": ["bardo"],
        "rarity_chances": dict(RARITY_T2),
        "affix_pools_to_use": ["bardo", "geral"],
    },
    "work_casaco_veludo_bardo": {
        "display_name": "Casaco de Veludo do Bardo",
        "emoji": "👕",
        "profession": "alfaiate",
        "level_req": 22,
        "time_seconds": 2400,
        "xp_gain": 150,
        "inputs": {"veludo_runico": 25, "fio_de_prata": 10, "gema_bruta": 5, "nucleo_forja_comum": 1},
        "result_base_id": "casaco_veludo_bardo",
        "unique": True,
        "class_req": ["bardo"],
        "rarity_chances": dict(RARITY_T2),
        "affix_pools_to_use": ["bardo", "geral"],
    },
    "work_calcas_veludo_bardo": {
        "display_name": "Calças de Veludo do Bardo",
        "emoji": "👖",
        "profession": "alfaiate",
        "level_req": 21,
        "time_seconds": 1500,
        "xp_gain": 120,
        "inputs": {"veludo_runico": 18, "fio_de_prata": 8, "nucleo_forja_comum": 1},
        "result_base_id": "calcas_veludo_bardo",
        "unique": True,
        "class_req": ["bardo"],
        "rarity_chances": dict(RARITY_T2),
        "affix_pools_to_use": ["bardo", "geral"],
    },
    "work_botas_veludo_bardo": {
        "display_name": "Botas de Veludo do Bardo",
        "emoji": "🥾",
        "profession": "alfaiate",
        "level_req": 20,
        "time_seconds": 900,
        "xp_gain": 70,
        "inputs": {"veludo_runico": 10, "couro_reforcado": 4, "nucleo_forja_comum": 1},
        "result_base_id": "botas_veludo_bardo",
        "unique": True,
        "class_req": ["bardo"],
        "rarity_chances": dict(RARITY_T2),
        "affix_pools_to_use": ["bardo", "geral"],
    },
    "work_luvas_veludo_bardo": {
        "display_name": "Luvas de Veludo do Bardo",
        "emoji": "🧤",
        "profession": "alfaiate",
        "level_req": 20,
        "time_seconds": 900,
        "xp_gain": 70,
        "inputs": {"veludo_runico": 10, "couro_reforcado": 4, "nucleo_forja_comum": 1},
        "result_base_id": "luvas_veludo_bardo",
        "unique": True,
        "class_req": ["bardo"],
        "rarity_chances": dict(RARITY_T2),
        "affix_pools_to_use": ["bardo", "geral"],
    },

    # --- Joias de Prata (Joalheiro) ---
    "work_anel_prata_bardo": {
        "display_name": "Anel de Prata do Bardo",
        "emoji": "💍",
        "profession": "joalheiro",
        "level_req": 23,
        "time_seconds": 1380,
        "xp_gain": 115,
        "inputs": {"barra_de_prata": 4, "gema_polida": 2, "nucleo_forja_comum": 1},
        "result_base_id": "anel_prata_bardo",
        "unique": True,
        "class_req": ["bardo"],
        "rarity_chances": dict(RARITY_T2),
        "affix_pools_to_use": ["bardo", "geral"],
    },
    "work_colar_prata_bardo": {
        "display_name": "Colar de Prata do Bardo",
        "emoji": "📿",
        "profession": "joalheiro",
        "level_req": 24,
        "time_seconds": 1560,
        "xp_gain": 140,
        "inputs": {"barra_de_prata": 3, "gema_polida": 3, "nucleo_forja_comum": 1},
        "result_base_id": "colar_prata_bardo",
        "unique": True,
        "class_req": ["bardo"],
        "rarity_chances": dict(RARITY_T2),
        "affix_pools_to_use": ["bardo", "geral"],
    },
    "work_brinco_prata_bardo": {
        "display_name": "Brinco de Prata do Bardo",
        "emoji": "🧿",
        "profession": "joalheiro",
        "level_req": 23,
        "time_seconds": 1200,
        "xp_gain": 100,
        "inputs": {"barra_de_prata": 2, "gema_polida": 1, "nucleo_forja_comum": 1},
        "result_base_id": "brinco_prata_bardo",
        "unique": True,
        "class_req": ["bardo"],
        "rarity_chances": dict(RARITY_T2),
        "affix_pools_to_use": ["bardo", "geral"],
    },
}
